apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.certificate.name }}
  namespace: {{ .Values.certificate.namespace }}
spec:
  # Secret names are always required.
  secretName: {{ .Values.certificate.secretName }}
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
    {{- toYaml .Values.certificate.organizations | nindent 4 }}
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  # At least one of a DNS Name, URI, or IP address is required.
  dnsNames:
  {{- toYaml .Values.certificate.dnsNames | nindent 2 }}
  uris:
  - spiffe://cluster.local/ns/sandbox/sa/example
  # Issuer references are always required.
  issuerRef:
    name: {{ .Values.clusterIssuer.name }}
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer