apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: argo-cd-application-controller-vs
spec:
  hosts:
  - argo-cd-argocd-application-controller
  gateways:
  - mesh
  http:
  - route:
    - destination:
        host: argo-cd-argocd-application-controller.{{ .Release.Namespace }}.svc.cluster.local