apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: argo-cd-redis-vs
spec:
  hosts:
  - argo-cd-argocd-redis
  gateways:
  - mesh
  http:
  - route:
    - destination:
        host: argo-cd-argocd-redis.{{ .Release.Namespace }}.svc.cluster.local