apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: argo-cd-repo-server
spec:
  hosts:
  - argo-cd-argocd-repo-server
  gateways:
  - mesh
  http:
  - route:
    - destination:
        host: argo-cd-argocd-repo-server.{{ .Release.Namespace }}.svc.cluster.local