apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: argocd-server-vs
spec:
  hosts:
  - {{ .Values.host }}
  gateways:
  - argocd-server-gateway
  http:
  - route:
    - destination:
        host: argo-cd-argocd-server.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: 80